export const TEACHER_STUDENT_PROFILES_REQUEST = "TEACHER_STUDENT_PROFILES_REQUEST";
export const TEACHER_STUDENT_PROFILES_SUCCESS = "TEACHER_STUDENT_PROFILES_SUCCESS";
export const TEACHER_STUDENT_PROFILES_FAIL = "TEACHER_STUDENT_PROFILES_FAIL";

export const TEACHER_HELPREQ_REQUEST = "TEACHER_HELPREQ_REQUEST";
export const TEACHER_HELPREQ_SUCCESS = "TEACHER_HELPREQ_SUCCESS";
export const TEACHER_HELPREQ_FAIL = "TEACHER_HELPREQ_FAIL";
